src/objects/Rule_Category__c/Rule_Category__c.object-meta.xml
<CustomObject>
    <label>Rule Category</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Rule Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rule_Category__c/fields/Rule_Category__c.field-meta.xml
<CustomField>
    <fullName>Rule_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Category_Library_Mapping__c/Rule_Category_Library_Mapping__c.object-meta.xml
<CustomObject>
    <label>Rule Category-Library Mapping</label>
    <nameField>
        <displayFormat>MAP-{0000}</displayFormat>
        <label>Rule Category-Library Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Category-Library Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rule_Category_Library_Mapping__c/fields/Rule_Category__c.field-meta.xml
<CustomField>
    <fullName>Rule_Category__c</fullName>
    <label>Rule Category</label>
    <referenceTo>Rule_Category__c</referenceTo>
    <relationshipLabel>Rule Category-Library Mappings</relationshipLabel>
    <relationshipName>Rule_Category_Library_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Rule_Category_Library_Mapping__c/fields/Rule_Library__c.field-meta.xml
<CustomField>
    <fullName>Rule_Library__c</fullName>
    <label>Rule Library</label>
    <referenceTo>Rule_Library__c</referenceTo>
    <relationshipLabel>Rule Category-Library Mappings</relationshipLabel>
    <relationshipName>Rule_Category_Library_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Rule_Combination__c/Rule_Combination__c.object-meta.xml
<CustomObject>
    <label>Rule Combination</label>
    <nameField>
        <displayFormat>EXPR-{0000}</displayFormat>
        <label>Rule Combination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Combinations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Rule_Combination__c/fields/Rule_Combination__c.field-meta.xml
<CustomField>
    <fullName>Rule_Combination__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Combination</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Rule_Library__c/Rule_Library__c.object-meta.xml
<CustomObject>
    <label>Rule Library</label>
    <nameField>
        <displayFormat>RULE-{0000}</displayFormat>
        <label>Rule Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SmartLogic_Category_API_Name__c/SmartLogic_Category_API_Name__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to map the category names with API Names for SObject</description>
    <label>SmartLogic Category API Name</label>
</CustomObject>

src/objects/SmartLogic_Category_API_Name__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/SOAP_Note__c/SOAP_Note__c.object-meta.xml
<CustomObject>
    <label>SOAP Note</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>SOAP Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOAP Note</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSmartLogicController.cls
@isTest
public class TestSmartLogicController {
	@testSetup 
	public static void setup() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
		User u = new User(Alias = 'standt', Email='Attestationuser@testorg.com', 
				EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
				LocaleSidKey='en_US', ProfileId = p.Id, 
				TimeZoneSidKey='America/Los_Angeles', UserName='Attestationuser@testorg.com');
		insert u;
		//Create custom settings record for category name
		SmartLogic_Category_API_Name__c categoryAPIName = new SmartLogic_Category_API_Name__c(Name='SOAP Notes',API_Name__c='SOAP_Note__c');
		insert categoryAPIName;

		//Create Rule Category Record
		Rule_Category__c ruleCategory = TestUtilityCls.getRuleCatagory('Test0001','SOAP Notes','Review of Systems');
		insert ruleCategory;

		//Create Rule Library Record
		Rule_Library__c rule = TestUtilityCls.getRuleLibrary('Regularly_Irregular','=','True,Yes,1','I48.91','Atrial Fibrillation','U','TesrR00001');
		insert rule;

		//Create Rule Library Category mapping record
		Rule_Category_Library_Mapping__c ruleMapping = TestUtilityCls.getRuleLibraryCategoryMapping(ruleCategory.id,rule.id);
		insert ruleMapping;

		//Create Rule Library Record
		Rule_Library__c rule2 = TestUtilityCls.getRuleLibrary('Chest Pain','=','True,Yes,1','I20.9','Angina, stable','U','TesrR00002');
		insert rule2;
		//Create Rule Library Category mapping record
		Rule_Category_Library_Mapping__c ruleMapping2 = TestUtilityCls.getRuleLibraryCategoryMapping(ruleCategory.id,rule2.id);
		insert ruleMapping2;

		//Create Rule Library Record
		Rule_Library__c rule3 = TestUtilityCls.getRuleLibrary('Wheezing','=','True,Yes,1','J44.9','Chronic obstructive pulmonary disease, unspecified','U','TesrR00003');
		insert rule3;

		//Create Rule Library Category mapping record
		Rule_Category_Library_Mapping__c ruleMapping3 = TestUtilityCls.getRuleLibraryCategoryMapping(ruleCategory.id,rule3.id);
		insert ruleMapping3;

		//Create Rule Library Record
		Rule_Library__c rule4 = TestUtilityCls.getRuleLibrary('Test Symp','=','True,Yes,1','','','U','TesrR00004',false);
		insert rule4;

		//Create Rule Library Category mapping record
		Rule_Category_Library_Mapping__c ruleMapping4 = TestUtilityCls.getRuleLibraryCategoryMapping(ruleCategory.id,rule4.id);
		insert ruleMapping4;

		//Create Rule Combination Record
		Rule_Combination__c ruleCombination = TestUtilityCls.getRuleCombination('U','TesrR00001 OR TesrR00002','(Regularly_Irregular = True,Yes,1) OR (Chest Pain = True,Yes,1)','TestRC00001','Angina, stable','I20.9');
		insert ruleCombination;
        
        System.assert(true);
	}
    
	public static testMethod void testGetSmartDiagnosys(){
		SmartLogicRequest slRequest = new SmartLogicRequest();
		slRequest.category = 'SOAP Notes';
		slRequest.symptoms = new Map<String,String> ();
		slRequest.ruleTypes = new List<String>();
		slRequest.ruleTypes.add('Review of Systems');
		slRequest.symptoms.put('Wheezing','Yes');
		slRequest.symptoms.put('Chest Pain','True');
		slRequest.symptoms.put('Regularly_Irregular','1');
		slRequest.symptoms.put('Test Symp','True,Yes,1');
		SmartLogicResponse slResponse = SmartLogicController.getSmartDiagnosis(slRequest);
		analyseResults(slResponse);

	}
	public static testMethod void testGetSmartDiagnosysNoResult(){
		SmartLogicRequest slRequest = new SmartLogicRequest();
		slRequest.category = 'SOAP Notes';
		slRequest.symptoms = new Map<String,String> ();
		slRequest.ruleTypes = new List<String>();
		slRequest.ruleTypes.add('Review of Systems');
		slRequest.symptoms.put('Wheezing','No');
		slRequest.symptoms.put('Chest Pain','False');
		slRequest.symptoms.put('Regularly_Irregular','0');
		slRequest.symptoms.put('gender','U'); 
		SmartLogicResponse slResponse = SmartLogicController.getSmartDiagnosis(slRequest);
		System.assert(slResponse.diagnosisResults.size()==0);

	}
	public static testMethod void testGetSmartDiagnosysNegative(){
		SmartLogicRequest slRequest = new SmartLogicRequest();
		slRequest.category = 'SOAP Notes1';
		slRequest.ruleTypes = new List<String>();
		slRequest.ruleTypes.add('Review of Systems');
		SmartLogicResponse slResponse = SmartLogicController.getSmartDiagnosis(slRequest);
		analyseResults(slResponse);
	}
	public static testMethod void testGetSmartDiagnosysNegativeNoSym(){
		SmartLogicRequest slRequest = new SmartLogicRequest();
		slRequest.category = 'SOAP Notes1';
		slRequest.ruleTypes = new List<String>();
		slRequest.symptoms = new Map<String,String> ();
		slRequest.ruleTypes.add('Review of Systems');
		SmartLogicResponse slResponse = SmartLogicController.getSmartDiagnosis(slRequest);
		analyseResults(slResponse);
	}

	public static void analyseResults(SmartLogicResponse response) {
		System.debug('response.isError: '+response.isError);
		System.debug('response.message: '+response.message);
		if(response.isError) {
			System.debug('Error::' + response.message);
			System.assert(true);
		}
		else if(response.diagnosisResults.size() > 0) {
			for(SmartLogicResponse.SmartDiagnosisResult result : response.diagnosisResults) {
				System.assert('J44.9'.equalsIgnoreCase(result.ICD)||'I20.9'.equalsIgnoreCase(result.ICD)||'I48.91'.equalsIgnoreCase(result.ICD));
			}
		}
		else {
			System.assert(false);
		}

	}
}