src/objects/Acronym_mapping__c/Acronym_mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to Store</description>
    <label>Acronym mapping</label>
</CustomObject>

src/objects/Acronym_mapping__c/fields/Acronym_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Acronym_Replacement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Acronym Replacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/configurations__mdt/configurations__mdt.object-meta.xml
<CustomObject>
    <description>Metadata type will be used to store all static config values</description>
    <label>configurations</label>
    <pluralLabel>configurations</pluralLabel>
</CustomObject>

src/objects/Global_Favorite_Searches__c/Global_Favorite_Searches__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settimng used to store the Favorite Searches</description>
    <label>Global Favorite Searches</label>
</CustomObject>

src/objects/Global_Favorite_Searches__c/fields/Favorite_Search_Text__c.field-meta.xml
<CustomField>
    <fullName>Favorite_Search_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Favorite Search Text</label>
    <type>TextArea</type>
</CustomField>

src/objects/Global_Favorites__c/Global_Favorites__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to store global favorite List</description>
    <label>Global Favorites Diagnosis</label>
</CustomObject>

src/objects/Global_Favorites__c/fields/ICD_Description__c.field-meta.xml
<CustomField>
    <fullName>ICD_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ICD Description</label>
    <type>TextArea</type>
</CustomField>

src/objects/ICD_HCC_mapping__c/ICD_HCC_mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store ICD 10 code mapping with their corresponding HCC Code</description>
    <label>ICD-HCC mapping</label>
</CustomObject>

src/objects/ICD_HCC_mapping__c/fields/HCC_code__c.field-meta.xml
<CustomField>
    <fullName>HCC_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>HCC code</label>
    <type>TextArea</type>
</CustomField>

src/objects/ICD_HCC_mapping__c/fields/HCC_Description__c.field-meta.xml
<CustomField>
    <fullName>HCC_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>HCC Description</label>
    <type>TextArea</type>
</CustomField>

src/objects/User_Favorites__c/User_Favorites__c.object-meta.xml
<CustomObject>
    <description>To store user&apos;s favorite searches</description>
    <label>User Favorites</label>
    <nameField>
        <displayFormat>UF-{0000}</displayFormat>
        <label>User Favorites Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Favorites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User_Favorites__c/fields/ICD_Code__c.field-meta.xml
<CustomField>
    <fullName>ICD_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ICD Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/User_Favorites__c/fields/Search_String__c.field-meta.xml
<CustomField>
    <fullName>Search_String__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Search String</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/classes/CodeSearchControllerTest.cls
@isTest
public class CodeSearchControllerTest {       
    
    @testSetup 
    public static void setup() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='Attestationuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='Attestationuser@testorg.com');
        insert u;
        
        Global_Favorites__c oGlobalFavoritesDiagnosis = new Global_Favorites__c(name='E21.1', ICD_Description__c='Secondary Hyperparathyroidism');
        insert oGlobalFavoritesDiagnosis;
        
        Global_Favorite_Searches__c oGlobalFavoritesSearches = new Global_Favorite_Searches__c(name='fract', Favorite_Search_Text__c='Fract');
        insert oGlobalFavoritesSearches;
        
        ICD_HCC_mapping__c oICDHCCMapping = new ICD_HCC_mapping__c(name='C41.3', HCC_code__c = '18', HCC_Description__c='Description');
        insert oICDHCCMapping;
        
        Acronym_mapping__c oAcronymMapping = new Acronym_mapping__c(name='dm2', Acronym_Replacement__c='DM 2');
        insert oAcronymMapping;
        
        User_Favorites__c favRec = new User_Favorites__c(Search_String__c='femur', ICD_Code__c='');
        insert favRec;
    }
    
    //Method to verify if correct user Label is returned by the controller
    public static testMethod void testGetUserName(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                String userName = CodeSearchController.getUserName();
                String userName2 = SearchController.getUserName();
                System.assertEquals(UserInfo.getName(), userName);
                System.assertEquals(UserInfo.getName(), userName2);
            }
        test.stopTest();
    }
    
    //Method to verify if ICD 9 code search is enabled and retryuned by the controller
    public static testmethod void testIsICD09SearchEnabled(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                configurations__mdt oConfiguration = [SELECT value__c FROM configurations__mdt WHERE DeveloperName = 'Enable_ICD09_Search'];
                System.assert(oConfiguration != null);
                boolean configValue = CodeSearchController.isICD9SearchEnabled();
                System.assertEquals(oConfiguration.value__c, String.valueOf(configValue));
             }
        test.stopTest();
    }
    
    //Method to verify if IICD 10 tree view is enabled and retryuned by the controller
    public static testmethod void testIsIICD10TreeViewEnabled(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                configurations__mdt oConfiguration = [SELECT value__c FROM configurations__mdt WHERE DeveloperName = 'Enable_ICD10_Tree_View'];
                System.assert(oConfiguration != null);
                boolean configValue = CodeSearchController.isICD10TreeViewEnabled();
                System.assertEquals(oConfiguration.value__c, String.valueOf(configValue));
            }
        test.stopTest();
    }
    
    //Test fetching Global Configurations on the Controller
     public static testmethod void testGetAllConfigurations(){
        List<configurations__mdt> lstMetaDataConfigurations = new List<configurations__mdt>();
        
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                lstMetaDataConfigurations = [SELECT value__c FROM configurations__mdt];
                Map<string,String> allConfigs = CodeSearchController.getAllConfigurations();
                
                System.assert(allConfigs.containsKey('User_Name'));
                System.assertEquals(UserInfo.getName() , allConfigs.get('User_Name'));    
                System.assertEquals(lstMetaDataConfigurations.size() + 1 , allConfigs.size());    
            }
        test.stopTest();
      }
      
      //Test fetching Global Configurations on the Controller
     public static testmethod void testFetchGlobalFavorites(){
        List<configurations__mdt> lstMetaDataConfigurations = new List<configurations__mdt>();
        
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                Map<String, List<Node>> allConfigs = CodeSearchController.fetchGlobalFavorites();
                System.assert(allConfigs.size() > 0);
             }
        test.stopTest();
      }
    
     //Test fetching My Favorites on the Controller
     public static testmethod void testGetMyFavorites(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                String data = MyFavoritesController.getMyFavorites();
                System.assertNotEquals(null, data);
             }
        test.stopTest();
      }
    
    //Test fetching Add To My Favorites on the Controller
     public static testmethod void testAddToMyFavorites(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                String data = MyFavoritesController.addToMyFavorites('','fever');
                System.assertEquals('SUCCESS', data);
                Map<String,Boolean> userFavoritesCache = new Map<String,Boolean>();
                Cache.Session.put('userFavoritesCache', userFavoritesCache);
                String data1 = MyFavoritesController.addToMyFavorites('I11','');
                System.assertEquals('DUPLICATE_MYFAVORITES', data1);
             }
        test.stopTest();
      }
    
    //Test fetching Remove To My Favorites on the Controller
     public static testmethod void testRemoveFromMyFavorites(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                String data = MyFavoritesController.removeFromMyFavorites('','femur');
                System.assertEquals('SUCCESS', data);
             }
        test.stopTest();
      }
    
    //Test jsonCallout
     public static testmethod void testjsonCallout(){
        User oUser = [SELECT ID FROM User WHERE Email='Attestationuser@testorg.com' LIMIT 1];
        test.StartTest();
            System.runAs(oUser)
            {
                SearchAPI util = new SearchAPI();
                util.getJSONSearchResults('femur');
                System.assert(true);
             }
        test.stopTest();
      }
    
}