src/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>{00000000}{YYMMDD}</displayFormat>
        <label>Engagement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rule_Category__c/Rule_Category__c.object-meta.xml
<CustomObject>
    <label>Rule Category</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Rule Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rule_Category__c/fields/Rule_Category__c.field-meta.xml
<CustomField>
    <fullName>Rule_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Category__c/fields/Rule_Category_Ext_ID__c.field-meta.xml
<CustomField>
    <fullName>Rule_Category_Ext_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Rule Category Ext ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Rule_Category__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Category_Library_Mapping__c/Rule_Category_Library_Mapping__c.object-meta.xml
<CustomObject>
    <label>Rule Category-Library Mapping</label>
    <nameField>
        <displayFormat>MAP-{0000}</displayFormat>
        <label>Rule Category-Library Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Category-Library Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rule_Category_Library_Mapping__c/fields/Rule_Category__c.field-meta.xml
<CustomField>
    <fullName>Rule_Category__c</fullName>
    <label>Rule Category</label>
    <referenceTo>Rule_Category__c</referenceTo>
    <relationshipLabel>Rule Category-Library Mappings</relationshipLabel>
    <relationshipName>Rule_Category_Library_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Rule_Category_Library_Mapping__c/fields/Rule_Library__c.field-meta.xml
<CustomField>
    <fullName>Rule_Library__c</fullName>
    <label>Rule Library</label>
    <referenceTo>Rule_Library__c</referenceTo>
    <relationshipLabel>Rule Category-Library Mappings</relationshipLabel>
    <relationshipName>Rule_Category_Library_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Rule_Combination__c/Rule_Combination__c.object-meta.xml
<CustomObject>
    <label>Rule Combination</label>
    <nameField>
        <displayFormat>EXPR-{0000}</displayFormat>
        <label>Rule Combination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Combinations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Rule_Combination__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Rule_Combination__c/fields/Rule_Combination__c.field-meta.xml
<CustomField>
    <fullName>Rule_Combination__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Combination</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Rule_Combination__c/fields/Rule_Combination_Description__c.field-meta.xml
<CustomField>
    <fullName>Rule_Combination_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Combination Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Rule_Combination__c/fields/Rule_combination_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Rule_combination_Ext_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule combination Ext Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Combination__c/fields/Rule_ICD__c.field-meta.xml
<CustomField>
    <fullName>Rule_ICD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule ICD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Library__c/Rule_Library__c.object-meta.xml
<CustomObject>
    <label>Rule Library</label>
    <nameField>
        <displayFormat>RULE-{0000}</displayFormat>
        <label>Rule Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rule_Library__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Rule_Library__c/fields/Rule_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Rule_Diagnosis__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Library__c/fields/Rule_Field__c.field-meta.xml
<CustomField>
    <fullName>Rule_Field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Library__c/fields/Rule_Gender__c.field-meta.xml
<CustomField>
    <fullName>Rule_Gender__c</fullName>
    <label>Rule Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Rule_Library__c/fields/Rule_Library_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Rule_Library_Ext_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Rule Library Ext Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Rule_Library__c/fields/Rule_Operator__c.field-meta.xml
<CustomField>
    <fullName>Rule_Operator__c</fullName>
    <label>Rule Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>STARTS WITH</fullName>
            </value>
            <value>
                <fullName>CONTAINS</fullName>
            </value>
            <value>
                <fullName>:</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Rule_Library__c/fields/Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Rule_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Rule_Library__c/fields/Works_with_Rule_Combinations_Only__c.field-meta.xml
<CustomField>
    <fullName>Works_with_Rule_Combinations_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Works with Rule Combinations Only</label>
    <type>Checkbox</type>
</CustomField>

src/objects/SmartLogic_Category_API_Name__c/SmartLogic_Category_API_Name__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to map the category names with API Names for SObject</description>
    <label>SmartLogic Category API Name</label>
</CustomObject>

src/objects/SmartLogic_Category_API_Name__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/SOAP_Note__c/SOAP_Note__c.object-meta.xml
<CustomObject>
    <label>SOAP Note</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>SOAP Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOAP Note</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRulesEngine.cls
@isTest
public with sharing class TestRulesEngine {

	@testSetup  
	public static void setup() {
		List<Rule_Category__c> lstRuleCategory = new List<Rule_Category__c>();
		List<Rule_Library__c> lstRuleLibarry = new List<Rule_Library__c>();
		List<Rule_Category_Library_Mapping__c> lstRuleCategoryLibraryMapping = new List<Rule_Category_Library_Mapping__c>();
		List<Rule_Combination__c> lstRuleCombination = new list<Rule_Combination__c>();

		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
		User u = new User(Alias = 'standt', Email='Attestationuser@testorg.com', 
				EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
				LocaleSidKey='en_US', ProfileId = p.Id, 
				TimeZoneSidKey='America/Los_Angeles', UserName='Attestationuser1@testorg.com');
		insert u;

		lstRuleCategory.add(new Rule_Category__c(Rule_Category_Ext_ID__c='CAT1', Rule_Category__c='SOAP Notes', Rule_Type__c='Review of Systems'));
		lstRuleCategory.add(new Rule_Category__c(Rule_Category_Ext_ID__c='CAT2', Rule_Category__c='SOAP Notes', Rule_Type__c='Physical Exam'));
		lstRuleCategory.add(new Rule_Category__c(Rule_Category_Ext_ID__c='CAT3', Rule_Category__c='Global', Rule_Type__c='Global'));
		lstRuleCategory.add(new Rule_Category__c(Rule_Category_Ext_ID__c='CAT4', Rule_Category__c='SOAP Notes', Rule_Type__c='SocialHx'));
		lstRuleCategory.add(new Rule_Category__c(Rule_Category_Ext_ID__c='CAT5', Rule_Category__c='Engagement', Rule_Type__c='Medication'));
		upsert lstRuleCategory;

		lstRuleLibarry.add(new Rule_Library__c(Rule_Library_Ext_Id__c='R1', is_Active__c=true, Rule_Field__c='Hearing Loss', Rule_Operator__c='=', Rule_Value__c='Bilateral', Rule_ICD__c='H91.90', Rule_Diagnosis__c='Hearing Loss', Rule_Gender__c='U', Works_with_Rule_Combinations_Only__c=false));
		lstRuleLibarry.add(new Rule_Library__c(Rule_Library_Ext_Id__c='R2', is_Active__c=true, Rule_Field__c='Morning Stiffness', Rule_Operator__c='=', Rule_Value__c='Yes', Rule_ICD__c='', Rule_Diagnosis__c='', Rule_Gender__c='', Works_with_Rule_Combinations_Only__c=true));
		lstRuleLibarry.add(new Rule_Library__c(Rule_Library_Ext_Id__c='R3', is_Active__c=true, Rule_Field__c='Morning Stiffness How Long', Rule_Operator__c='=', Rule_Value__c='1', Rule_ICD__c='', Rule_Diagnosis__c='', Rule_Gender__c='', Works_with_Rule_Combinations_Only__c=true));
		lstRuleLibarry.add(new Rule_Library__c(Rule_Library_Ext_Id__c='R4', is_Active__c=true, Rule_Field__c='Joint Swelling', Rule_Operator__c='=', Rule_Value__c='True', Rule_ICD__c='', Rule_Diagnosis__c='', Rule_Gender__c='', Works_with_Rule_Combinations_Only__c=true));
		lstRuleLibarry.add(new Rule_Library__c(Rule_Library_Ext_Id__c='R5', is_Active__c=false, Rule_Field__c='Hearing Loss', Rule_Operator__c='=', Rule_Value__c='Test Symp', Rule_Gender__c='U', Works_with_Rule_Combinations_Only__c=false));

		upsert lstRuleLibarry;

		lstRuleCombination.add(new Rule_Combination__c(Is_Active__c=true, Gender__c='U', Rule_combination_Ext_Id__c='EXP1', Rule_Combination__c='(R2 AND R3) OR R4', Rule_Combination_Description__c='((Morning Stiffness = True,Yes,1) AND (Morning Stiffness How Long > 1) ) OR (Joint Swelling = True,Yes,1)', Rule_ICD__c='M06.9', Rule_Diagnosis__c='Arthritis-Rheumatoid'));
		lstRuleCombination.add(new Rule_Combination__c(Is_Active__c=true, Gender__c='U', Rule_combination_Ext_Id__c='EXP2', Rule_Combination__c='(R2 AND R3) AND R4', Rule_Combination_Description__c='((Morning Stiffness = True,Yes,1) AND (Morning Stiffness How Long > 1) ) AND (Joint Swelling = True,Yes,1)', Rule_ICD__c='M06.91', Rule_Diagnosis__c='Arthritis-Rheumatoid type 1'));
		
        lstRuleCombination.add(new Rule_Combination__c(Is_Active__c=false, Gender__c='U', Rule_combination_Ext_Id__c='EXP3', Rule_Combination__c='(R1 AND R2) OR R5', Rule_Combination_Description__c='((Hearing Loss = True,Yes,1) AND (Morning Stiffness = True,Yes,1) ) OR (Hearing Loss = True,Yes,1)', Rule_ICD__c='M06.9', Rule_Diagnosis__c='Arthritis-Rheumatoid'));
		lstRuleCombination.add(new Rule_Combination__c(Is_Active__c=false, Gender__c='U', Rule_combination_Ext_Id__c='EXP4', Rule_Combination__c='(R1 AND R2) AND R5', Rule_Combination_Description__c='((Hearing Loss = True,Yes,1) AND (Morning Stiffness = True,Yes,1) ) AND (Hearing Loss = True,Yes,1)', Rule_ICD__c='M06.91', Rule_Diagnosis__c='Arthritis-Rheumatoid type 1'));
		lstRuleCombination.add(new Rule_Combination__c(Is_Active__c=true, Gender__c='U', Rule_combination_Ext_Id__c='EXP5', Rule_Combination__c='(R1 AND EXP2)', Rule_Combination_Description__c='((Hearing Loss = True,Yes,1) AND (Morning Stiffness = True,Yes,1) ) AND (Hearing Loss = True,Yes,1)', Rule_ICD__c='M06.91', Rule_Diagnosis__c='Arthritis-Rheumatoid type 1'));
        upsert lstRuleCombination;

		String testRuleType = 'Physical Exam';
		List<Rule_Category__c>  categoryList = [Select id from Rule_Category__c where Rule_Type__c = :testRuleType];

		List<Rule_Category_Library_Mapping__c> lstCategoryMapping =  new   List<Rule_Category_Library_Mapping__c>();
		for(Rule_Library__c ruleObj : lstRuleLibarry) {
			Rule_Category_Library_Mapping__c mapping = new Rule_Category_Library_Mapping__c();
			mapping.Rule_Library__c = ruleObj.id;
			mapping.Rule_Category__c = categoryList.get(0).id;
			lstCategoryMapping.add(mapping);
		}
		upsert lstCategoryMapping;	
		List<SmartLogic_Category_API_Name__c> allSettings = new List<SmartLogic_Category_API_Name__c>();
		allSettings.add(new SmartLogic_Category_API_Name__c(API_Name__c = 'SOAP_Note__c',Name = 'SOAP Notes'));
		allSettings.add(new SmartLogic_Category_API_Name__c(API_Name__c = 'Engagement__c',Name = 'Engagement'));
		insert allSettings;
	}

}