src/objects/Skin_Abnormality__c/Skin_Abnormality__c.object-meta.xml
<CustomObject>
    <label>Skin Abnormality</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Skin Abnormality Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skin Abnormality</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skin_Abnormality__c/fields/SOAP_Note__c.field-meta.xml
<CustomField>
    <fullName>SOAP_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Soap Note</label>
    <referenceTo>SOAP_Note__c</referenceTo>
    <relationshipLabel>Skin Abnormality</relationshipLabel>
    <relationshipName>Skin_Abnormality</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/SOAP_Note__c/SOAP_Note__c.object-meta.xml
<CustomObject>
    <label>SOAP Note</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>SOAP Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOAP Note</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RulesEngineConstants.cls
public class RulesEngineConstants {
	public static final String LOGICAL_OPERATORS = 'AND,OR,and,or,';
	public static final String Yes_No_Values = 'yes,no,true,false,YES,NO,True,False,TRUE,FALSE,Yes,No,1,0';
	public static final String COMBINATION_OPERATORS = '{,},(,)';
	public static final String SOURCE_RULE = 'rule';
	public static final String SOURCE_RULE_COMBINATION = 'combination';
	public static final String SOURCE_OPTUM360_API = 'optum360';
	public static final Set<String> setSOAPNotesRelatedObjects = new Set<String>{'Skin_Abnormality__c', 'SOAP_Note__c'};
}